### ISSUE TITLE
URL Schemes in Logseq block content were broken in Anki cards

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#179] opened 2023-05-08 23:48 UTC
Describe the bug
The MarginNote3 URL Schemes were broken after converting to Anki.
Specifically, see the below pictures:
This is original content in Logseq:
image
This is Anki card content, and I have labeled the broken URL Scheme with arrows
image

Device Information (please complete the following information):

OS with version: macos 12.2.1
Logseq Anki Sync Plugin Version: 2.72
Anki Version: 2.4.19
AnkiConnect Addon Version: Latest
Logseq Version:0.7.2

**Comment by debanjandhar12** [comment] 2023-05-12 16:39
Duplicate of https://github.com/debanjandhar12/logseq-anki-sync/issues/74. Will be fixed in V4.6.0.

**Closed by debanjandhar12** 2023-05-12 16:39 UTC
Labels: bug
