### ISSUE TITLE
Suggestion for this feature.

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#178] opened 2023-05-07 14:00 UTC
"Possible fix for the missing file:// and booknote: issues."
"Maybe enabling it is enough, this line of code is just a replacement. However, I have forgotten most of my JavaScript skills, so the issue might be with the built-in 'converterToHTMLFile' function. It might be necessary to patch it early and change "//" to "\/\/"."

![({QB5RJ) 8G5)C1R)LL0@AE](https://user-images.githubusercontent.com/103982843/236681985-f90aa950-2703-4c53-b9af-2ce2db8ab96d.png)

**Comment by debanjandhar12** [comment] 2023-05-12 16:38
Duplicate of https://github.com/debanjandhar12/logseq-anki-sync/issues/74. Will be fixed in V4.6.0.

**Closed by debanjandhar12** 2023-05-12 16:38 UTC
Labels: enhancement
