### ISSUE TITLE
Zotero link not working in generated card

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#180] opened 2023-05-11 04:53 UTC
**Describe the bug**
The link to an specific zotero item in the card generated by the plugin is not working properly. When click the link it won't jump to the specific the zotero item the link is referring to(It open the Zotero app though). As oppose to the link will work properly if manually create card in anki (and created a hyperlink with URL to be the zotero item link), which makes me feel that it is plugin specific issue.

**Steps to Reproduce:**

1. create a card with markdown syntax for link, with the link being specific zotero item.
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/16418270/46fbfb92-273a-4e94-9c97-4952a0edbc2a)

2. use plugin to generate card.
3. click the link in the card in Anki. And it only opens zotero app
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/16418270/97a5c542-d86d-432a-b1ca-bbc25950015e)

**Expected behavior**
When click the link it should open up Zotero as well as jumping to the corresponding zotero item.

**Comment by chs33** [comment] 2023-05-11 05:01
after checking the url the plugin is generated it is the same with this [issue](https://github.com/debanjandhar12/logseq-anki-sync/issues/176#issue-1697275221). The url in card generated in above example is "zotero:select/library/items/KFVN65ND",i.e. losing "//" which make it not working.

**Comment by debanjandhar12** [comment] 2023-05-12 16:37
Duplicate of https://github.com/debanjandhar12/logseq-anki-sync/issues/74. Will be fixed in V4.6.0.

**Closed by debanjandhar12** 2023-05-12 16:37 UTC
Labels: bug
