### ISSUE TITLE
Export the link, two // conform, resulting in a link error

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#173] opened 2023-04-29 23:38 UTC
logseq:_//_graph/skyfox?page=card
bookxnotepro:opennote/?nb={4a25917c-5f32-449b-ab7b-24d07915414e}&amp;book=e62e029df01f8b3452c221a84cfce74f&amp;page=30&amp;x=402&amp;y=1152&amp;id=26&amp;uuid=c0968eb7f9326254bb5d7d0e0bbc485e
bookxnotepro: there should be //
**Device Information (please complete the following information):**
 - OS with version: [e.g. Windows 11 Home 21H2] 
 - Logseq Anki Sync Plugin Version: [e.g. 0.3.3]
 - Anki Version: [e.g. 2.1.49]
 - AnkiConnect Addon Version: [e.g. 2.1.0]
 - Logseq Version: [e.g. 0.5.9]

**Comment by debanjandhar12** [comment] 2023-05-02 10:09
Duplicate of #74

**Closed by debanjandhar12** 2023-05-02 10:09 UTC
Labels: bug
