### ISSUE TITLE
Syncing from Logseq to Anki will lose "file://"

### ISSUE THREAD

**Issue by keen0309** [debanjandhar12/logseq-anki-sync#177] opened 2023-05-05 11:01 UTC
Syncing from Logseq to Anki will lose "file://"and sending it to Anki makes it disappear.

![image](https://user-images.githubusercontent.com/103982843/236440703-9f4b2792-9154-46f1-831d-2fbaadf55fb3.png)

**Comment by debanjandhar12** [comment] 2023-05-12 16:38
Duplicate of https://github.com/debanjandhar12/logseq-anki-sync/issues/74. Will be fixed in V4.6.0.

**Closed by debanjandhar12** 2023-05-12 16:38 UTC
Labels: bug
