### ISSUE TITLE
Setup fails - Error: [deferred timeout] async call #3074/804

### ISSUE THREAD

**Issue by yingzhu146** [debanjandhar12/logseq-anki-sync#61] opened 2022-04-09 13:07 UTC
Hi there - thanks a lot for the awesome plugin!

This might be the same issue as #23? Was closed/couldn't reopen so starting a new one here 

First got
<img width="534" alt="image" src="https://user-images.githubusercontent.com/59233975/162575354-af4bb020-8dae-4ee7-afc3-282b2add32d6.png">
then after restarting both anki/logseq
<img width="551" alt="image" src="https://user-images.githubusercontent.com/59233975/162575385-51e49a55-6628-483d-8d3f-5efcd2fff040.png">

Thanks a lot for the help!

Steps to Reproduce:

install anki sync from marketplace
download anki
install ankiconnector plugin for anki
Click "Sync button"
Give AnkiConnect addon permissions in anki app
Pop-up error message is shown
Open DevTools, shows error message above (same as popup)
Expected behavior

Developer console screenshot:
image

Device Information (please complete the following information):

OS with version:v1.0.0 on Macbook Air, Monterey
Logseq Anki Sync Plugin Version: 2.1.2
Anki Version: Version ⁨2.1.49 (dc80804a)⁩
AnkiConnect Addon Version: not sure where to get, but I just installed today with 2055492159
Logseq Version:0.6.5

**Comment by debanjandhar12** [comment] 2022-05-04 06:52
Duplicate of #58. Thanks for the report. However, please discuss in #58 instead.

**Closed by debanjandhar12** 2022-05-04 06:52 UTC
Labels: bug
